### ISSUE TITLE
Cannot import freeRASP SDK on android project

### ISSUE THREAD

**Issue by Horobi01** [talsec/Free-RASP-Community#52]
Hi,
I'm trying to import freeRASP SDK on my Android project, i'm also following the documentation but when i sync the gradle file and try to continue it's like the SDK was not downloaded and imported into my project.

Also, when i go to JitPack or into my browser and i type this url "https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp" that is the url in the documentation, it gives me not found.

**Comment by xprikryl2** [comment]
Hello @Horobi01,

I checked the repository's state, but I couldn't find any downtime (and it is currently running). You won't be able to access the URL specified above directly because we do not have browsing of the repository enabled.

Let's say that you want to download version 9.6.0 of our library. Your project will try to find the following pom file with the library's metadata. You can try if this URL is accessible: [https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community/9.6.0/TalsecSecurity-Community-9.6.0.pom](https://europe-west3-maven.pkg.dev/talsec-artifact-repository/freerasp/com/aheaditec/talsec/security/TalsecSecurity-Community/9.6.0/TalsecSecurity-Community-9.6.0.pom).

If the link above is not available, the issue can be in the network settings. If yes, it's probably in the project configuration. In that case, could you please share the full stack trace with the Gradle sync error?

Best regards,
Ondrej from Talsec

**Comment by Horobi01** [comment]
Hello @xprikryl2,

I have successfully imported the library in the android app, now i have a problem with the iOS app, becase i see that the framework is for swift app, but i have an objective-c app, is there a talsec framework for objective-c app?

**Comment by tomskypy** [comment]
Hi @Horobi01,

you can access Swift declarations in ObjC code by creating a bridging header, please refer to the [official docs](https://developer.apple.com/documentation/swift/importing-swift-into-objective-c) or [SO questions](https://www.google.com/search?q=swift+library+in+objective+c+site:stackoverflow.com) regarding this topic. If you have any further troubles don't hesitate to ask.

Best regards,
Tom from Talsec

**Comment by msikyna** [comment]
Hello @Horobi01 ,
did the proposed solution work? Thank you!

Kind regards,
Talsec team

**Comment by Horobi01** [comment]
Yes it worked! Thanks for the support
